on:
  schedule:
  - cron: "30 3,18,20,22 * * *"
  push:
    branches:
      - master

jobs:
  render:
    name: Run R update scripts
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
    
      - name: Checkout 
        uses: actions/checkout@v2    
      
      
      - name: Install packages
        run: |
          install.packages('remotes')
          remotes::install_cran("jsonlite")
          remotes::install_cran("dotenv")
          remotes::install_cran("janitor")
          remotes::install_cran("tidyverse")
          remotes::install_cran("googlesheets4")

        shell: Rscript {0}

      - name: Download  data
        run: Rscript R/generate_vaccine_data.R

        
      - name: Upload data
        run: Rscript R/upload_vaccine_data_to_google_sheets.R
        env: # Or as an environment variable
          google_key: ${{ secrets.GOOGLE_KEY }}
          google_sheets_id: ${{ secrets.GOOGLE_SHEETS_ID }}
          
          
      - name: Check for changes
        run: |
          if git diff --exit-code; then
            echo "changes_exist=false" >> $GITHUB_ENV
            echo "No changes detected"
          else
            echo "changes_exist=true" >> $GITHUB_ENV
            echo "Changes detected and will be committed"

          fi
          
      - name: Push commits
        if: env.changes_exist == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update vaccine data (GH Actions)"
          git push

