on:
  schedule:
  - cron: "0 18 * * *"
  push:
    branches:
      - master
    paths:
      - '**.R'
  pull_request:
    branches:
      - main
    paths:
      - '**.R'
jobs:
  render:
    name: Run R update scripts
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
    
      - name: Checkout 
        uses: actions/checkout@v2    
      
      
      - name: Install packages
        run: |
          install.packages('remotes')
          remotes::install_cran("jsonlite")
          remotes::install_cran("dotenv")
          remotes::install_cran("janitor")
          remotes::install_cran("tidyverse")
          remotes::install_cran("googlesheets4")

        shell: Rscript {0}

      - name: Download  data
        run: Rscript R/generate_vaccine_data.R

        
      - name: Upload data
        run: Rscript R/upload_vaccine_data_to_google_sheets.R
        env: # Or as an environment variable
          google_key: ${{ secrets.GOOGLE_KEY }}
          google_sheets_id: ${{ secrets.GOOGLE_SHEETS_ID }}
          
      - name: Push commits
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update vaccine data (GH Actions)"
          git push

